redditclone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create, :index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

redditclone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  has_many :post_subs

  has_many :posts,
    through: :post_subs,
    source: :post

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User
end

redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :redirect_if_not_mod, only: [:edit, :update, :destroy]
  before_action :redirect_if_not_logged_in

  def new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def redirect_if_not_mod
    sub = Sub.find_by(id: params[:id])
    flash[:errors] = ['Insufficient permission to make change']
    redirect_to sub_url(sub) unless sub.moderator_id == current_user.id
  end

end

redditclone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render 'layouts/errors' %>

<form action="<%=sub_url(@sub)%>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>
    Title: <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label><br>

  <label>
    Description: <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label><br>

  <input type="submit" name="" value="Save Sub Changes">
</form>

redditclone/app/views/subs/index.html.erb
<h1>Subs Index Page</h1>

<% @subs.each do |sub| %>
  <p><a href="<%= sub_url(sub) %>"><%= sub.title %></a></p>
<% end %>

redditclone/app/views/subs/new.html.erb
<h1>Create New Sub</h1>

<%= render 'layouts/errors' %>

<form action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <label>
    Title: <input type="text" name="sub[title]" value="">
  </label><br>

  <label>
    Description: <input type="text" name="sub[description]" value="">
  </label><br>

  <input type="submit" name="" value="Create New Sub">
</form>

redditclone/app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>

<p>Description: <%= @sub.description %> </p>

<p>Moderator: <%= @sub.moderator.username %> </p>

<%= render 'layouts/errors' %><br>
<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>

<form action="<%= sub_url(@sub) %>" method="post">
  <%= auth_token %>
  <%= form_delete_hidden_input %>
  <input type="submit" name="" value="Delete Sub">
</form>


<% @sub.posts.each do |post| %>
  <a href="<%= post_url(post) %>"><%= post.title %></a><br/>
<% end %>