redditclone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create, :index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

redditclone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint(8)        not null, primary key
#  content           :string           not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post

  belongs_to :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

end

redditclone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find_by(id: params[:post_id])
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      if is_parent_comment?(@comment)
        redirect_to post_url(@comment.post)
      else
        redirect_to comment_url(@comment.parent_comment)
      end
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment_url(@comment.post)
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
    render :show
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

  def is_parent_comment?(comment)
    comment.parent_comment_id.nil?
  end
end

redditclone/app/views/comments/new.html.erb
<h1>Add Comments</h1>
<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <label>
    Comment: <input type="text" name="comment[content]" value="">
  </label>

  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <input type="submit" name="" value="Add Comment">
</form>

redditclone/app/views/comments/show.html.erb
<h1>Comment Show Page</h1>

<p>Author: <%= @comment.author.username %><br/>
Content: <%= @comment.content %></p>

<h2>Child Comments</h2>
<% @comment.child_comments.each do |child_comment| %>
  <p>Author: <%= child_comment.author.username %><br/>
  Content: <%= child_comment.content %></p>
<% end %>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <label>Content:
    <input type="text" name="comment[content]" value="">
  </label>

  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">

  <input type="submit" name="" value="Add Child Comment">
</form>