redditclone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create, :index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

redditclone/app/views/layouts/_comment.html.erb
<ul>
  <li>Author: <%= comment.author.username %> | Content: <%= comment.content %> | <a href="<%= comment_url(comment) %>">See More</a>
  </li>

  <% @all_comments.each do |child_comment| %>
    <% if child_comment.parent_comment_id == comment.id %>
      <%= render 'layouts/comment', comment: child_comment %>
    <% end %>
  <% end %>

</ul>

redditclone/app/views/layouts/_errors.html.erb
<%= flash[:errors] if flash[:errors] %>

redditclone/app/views/layouts/_user_form.html.erb
<% if action == 'new_user' %>
  <% action_url = users_url %>
  <% submit_value = "Sign Up" %>
  <% header_message = "Sign Up" %>
<% else %>
  <% action_url = session_url %>
  <% submit_value = "Sign In" %>
  <% header_message = "Sign In" %>
<% end %>

<h1><%= header_message %></h1>

<%= render 'layouts/errors' %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <label>
    Username: <input type="text" name="user[username]" value="">
  </label>
  <label>
    Password: <input type="text" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="<%= submit_value %>">
</form>

redditclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <p>Welcome <%= current_user.username %></p>
      <form action="<%= session_url %>" method="post">
        <%= auth_token %>
        <%= form_delete_hidden_input %>
        <input type="submit" name="" value="Log Out">
      </form>
    <% end %>

    <%= yield %>
  </body>
</html>