redditclone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create, :index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

redditclone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id        :bigint(8)        not null, primary key
#  title     :string           not null
#  url       :string
#  content   :string
#  author_id :integer          not null
#

class Post < ApplicationRecord
  validates :title, :author_id, presence: true
  validates :post_subs, presence: true

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :comments

end

redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_if_not_author, only: [:edit, :update, :destroy]
  before_action :redirect_if_not_logged_in


  def new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @all_comments = @post.comments.includes(:author)
    render :show
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def redirect_if_not_author
    post = Post.find_by(id: params[:id])
    unless post.author_id == current_user.id
      flash[:errors] = ['Insufficient permission to make change']
      redirect_to post_url(post)
    end
  end

end

redditclone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'layouts/errors' %>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>
    Title: <input type="text" name="post[title]" value="<%= @post.title %>">
  </label><br>

  <label>
    URL: <input type="text" name="post[url]" value="<%= @post.url %>">
  </label><br>

  <label>
    Content: <input type="text" name="post[content]" value="<%= @post.content %>">
  </label><br>

  <label>Subs:
    <% subs = Sub.all %>
    <% subs.each do |sub| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
        <% if @post.subs.include?(sub) %>
          <%= "checked" %>
        <% end %>
      ><%= sub.title %>
    <% end %>

  </label>

  <input type="submit" name="" value="Save Changes">
</form>

redditclone/app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= render 'layouts/errors' %>

<form action="<%= sub_posts_url %>" method="post">
  <%= auth_token %>
  <label>
    Title: <input type="text" name="post[title]" value="">
  </label><br>

  <label>
    URL: <input type="text" name="post[url]" value="">
  </label><br>

  <label>
    Content: <input type="text" name="post[content]" value="">
  </label><br>

  <label>Subs:
    <% subs = Sub.all %>
    <% subs.each do |sub| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%= sub.title %>
    <% end %>

  </label>

  <input type="submit" name="" value="Create New Post">
</form>

redditclone/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>

<p>URL: <%= @post.url %> </p>

<p>Content: <%= @post.content%></p>

<p>Subs Cross-posted At:<br/>
  <% @post.subs.each do |sub| %>
    <%= sub.title %><br/>
  <% end %>
</p>

<p>Author: <%= @post.author.username%></p>

<%= render 'layouts/errors' %><br>
<a href="<%= edit_post_url(@post) %>">Edit Post</a>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <%= form_delete_hidden_input %>
  <input type="submit" name="" value="Delete Post">
</form>

<h2>Comments</h2>


<%# @post.comments.where(parent_comment_id: nil).each do |comment| %>
  <%#= render 'layouts/comment', comment: comment %>
<%# end %>


<% @all_comments.each do |comment| %>
  <% if comment.parent_comment_id.nil? %>
    <%= render 'layouts/comment', comment: comment %>
  <% end %>
<% end %>

<a href="<%= new_post_comment_url(@post) %>">Add Comment</a>